### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by nzjrs** [JosPolfliet/pandas-profiling#1]
Hi,

When I think of the verb 'Profiling' I think of compatible  projects like 'line_profiler', 'memory_profiler' or performance profiling. Given that pandas has a similar function called 'describe()' would it make sense to choose another name for this project?

John

**Comment by JosPolfliet** [comment]
['Data profiling'](https://en.wikipedia.org/wiki/Data_profiling) is a well known concept in data science. I specifically did not want to call it _describe_ since then we introduce confusion between this package and the original _describe_ function in pandas.

Something with EDA (exploratory data analysis) would be another route to take. 

Any other thoughts?
