### ISSUE TITLE
Customization Options

### ISSUE THREAD

**Issue by bradleyfay** [JosPolfliet/pandas-profiling#3]
Just tried out your package for a small project at work. I'm already a big fan of it as it accomplishes a great deal of what I would do in the pre-modeling phase with a single command. It also looks much nicer with the HTML format. 

Are you planning on adding some customization options? For example, it would be great to set the number of bins in the histograms. I work with some highly skewed data and getting a good visual tends to require a large amount of bins.

Additionally, crosstabs and scatter plots for bivariate descriptive analysis would be awesome. Maybe not by default, but the ability to specificy them using tuples of column names would be mighty useful.

**Comment by JosPolfliet** [comment]
Number of bins in a histogram is something I can easily add.

I won't add crosstabs, scatter plots and scatter matrices. They are very easy to create in pandas using the `scatter_matrix ` function. I would not see added value in adding an option to show them or not, since typing that extra parameter would almost be as much work for the user as just using the `scatter_matrix` function itself.

**Comment by JanSchulz** [comment]
It would add value if the resulting scatter{plot|matrix} would be better styled as the default :-)

**Comment by JosPolfliet** [comment]
Added optional bins= option.

**Comment by AniketBG** [comment]
How do i stop the Pearson and Spearman plots, i dont want that in my report. Is there any way to do  that?
